// @ts-nocheck -- skip type checking
import * as publicDocs_3 from "../content/docs/public/en/getting-started/index.mdx?collection=publicDocs&hash=1775147896989"
import * as publicDocs_2 from "../content/docs/public/el/getting-started/index.mdx?collection=publicDocs&hash=1775147896989"
import * as publicDocs_1 from "../content/docs/public/en/index.mdx?collection=publicDocs&hash=1775147896989"
import * as publicDocs_0 from "../content/docs/public/el/index.mdx?collection=publicDocs&hash=1775147896989"
import * as privateDocs_5 from "../content/docs/private/el/agency-guides/team-management.mdx?collection=privateDocs&hash=1775147896989"
import * as privateDocs_4 from "../content/docs/private/el/agency-guides/getting-started.mdx?collection=privateDocs&hash=1775147896989"
import * as privateDocs_3 from "../content/docs/private/en/agency-guides/team-management.mdx?collection=privateDocs&hash=1775147896989"
import * as privateDocs_2 from "../content/docs/private/en/agency-guides/getting-started.mdx?collection=privateDocs&hash=1775147896989"
import * as privateDocs_1 from "../content/docs/private/en/index.mdx?collection=privateDocs&hash=1775147896989"
import * as privateDocs_0 from "../content/docs/private/el/index.mdx?collection=privateDocs&hash=1775147896989"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const privateDocs = _runtime.docs<typeof _source.privateDocs>([{ info: {"path":"el/index.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/el/index.mdx"}, data: privateDocs_0 }, { info: {"path":"en/index.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/en/index.mdx"}, data: privateDocs_1 }, { info: {"path":"en/agency-guides/getting-started.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/en/agency-guides/getting-started.mdx"}, data: privateDocs_2 }, { info: {"path":"en/agency-guides/team-management.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/en/agency-guides/team-management.mdx"}, data: privateDocs_3 }, { info: {"path":"el/agency-guides/getting-started.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/el/agency-guides/getting-started.mdx"}, data: privateDocs_4 }, { info: {"path":"el/agency-guides/team-management.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/el/agency-guides/team-management.mdx"}, data: privateDocs_5 }], [{"info":{"path":"en/meta.json","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/en/meta.json"},"data":{"title":"Internal Guides","pages":["index","---Agency Operations---","agency-guides"]}}, {"info":{"path":"el/meta.json","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/el/meta.json"},"data":{"title":"Εσωτερικοί Οδηγοί","pages":["index","---Λειτουργία Γραφείου---","agency-guides"]}}, {"info":{"path":"en/agency-guides/meta.json","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/en/agency-guides/meta.json"},"data":{"title":"Agency Operations","pages":["getting-started","team-management"]}}, {"info":{"path":"el/agency-guides/meta.json","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/private/el/agency-guides/meta.json"},"data":{"title":"Λειτουργία Γραφείου","pages":["getting-started","team-management"]}}])
export const publicDocs = _runtime.docs<typeof _source.publicDocs>([{ info: {"path":"el/index.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/public/el/index.mdx"}, data: publicDocs_0 }, { info: {"path":"en/index.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/public/en/index.mdx"}, data: publicDocs_1 }, { info: {"path":"el/getting-started/index.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/public/el/getting-started/index.mdx"}, data: publicDocs_2 }, { info: {"path":"en/getting-started/index.mdx","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/public/en/getting-started/index.mdx"}, data: publicDocs_3 }], [{"info":{"path":"el/meta.json","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/public/el/meta.json"},"data":{"title":"Τεκμηρίωση","pages":["index","---Ξεκινώντας---","getting-started"]}}, {"info":{"path":"en/meta.json","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/public/en/meta.json"},"data":{"title":"Documentation","pages":["index","---Getting Started---","getting-started"]}}, {"info":{"path":"el/getting-started/meta.json","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/public/el/getting-started/meta.json"},"data":{"title":"Ξεκινώντας","pages":["index"]}}, {"info":{"path":"en/getting-started/meta.json","absolutePath":"/Users/stapo/Desktop/Oikion/MVP/content/docs/public/en/getting-started/meta.json"},"data":{"title":"Getting Started","pages":["index"]}}])