import { z } from "zod";

import {
  PropertyTypeEnum,
  TransactionTypeEnum,
  HeatingTypeEnum,
  EnergyCertClassEnum,
  PropertyConditionEnum,
  FurnishedStatusEnum,
  ItemVisibilityEnum,
} from "./property-import-schema";
import {
  zBoolean,
  zBooleanNullable,
  zOptionalPositiveNumber,
  zOptionalInt,
  zOptionalAnyInt,
  zOptionalDateString,
} from "./zod-helpers";

export const PropertyPurposeEnum = z.enum([
  "RESIDENTIAL",
  "COMMERCIAL",
  "LAND",
  "PARKING",
  "OTHER",
]);

export const TimelineEnum = z.enum([
  "IMMEDIATE",
  "ONE_THREE_MONTHS",
  "THREE_SIX_MONTHS",
  "SIX_PLUS_MONTHS",
]);

// Enum values matching Prisma schema
export const RequestStatusEnum = z.enum([
  "ACTIVE",
  "MATCHED",
  "UNDER_OFFER",
  "CLOSED",
  "PAUSED",
]);

export const RequestUrgencyEnum = z.enum([
  "LOW",
  "MEDIUM",
  "HIGH",
  "CRITICAL",
]);

/**
 * Request CSV Import Schema
 * Matches the fields from the Prisma Request model
 */
export const requestImportSchema = z.object({
  // User-provided ID (optional - will auto-generate if not provided)
  id: z.coerce.string().optional().or(z.literal("")),

  // Core optional field (auto-generated by engine if not provided)
  name: z.coerce.string().optional(),

  // Enums (all optional, nullable)
  transaction_type: TransactionTypeEnum.optional().nullable(),
  property_type: PropertyTypeEnum.optional().nullable(),
  property_purpose: PropertyPurposeEnum.optional().nullable(),
  status: RequestStatusEnum.optional().nullable(),
  urgency: RequestUrgencyEnum.optional().nullable(),
  timeline: TimelineEnum.optional().nullable(),
  energy_cert_min: EnergyCertClassEnum.optional().nullable(),
  furnished: FurnishedStatusEnum.optional().nullable(),

  // Array enums (arrive pre-split from normalizer)
  condition: z.array(PropertyConditionEnum).optional().nullable(),
  heating_type: z.array(HeatingTypeEnum).optional().nullable(),

  // Range numerics (all optional, nullable, with European format support)
  budget_min: zOptionalPositiveNumber,
  budget_max: zOptionalPositiveNumber,
  size_min_sqm: zOptionalPositiveNumber,
  size_max_sqm: zOptionalPositiveNumber,
  plot_size_min_sqm: zOptionalPositiveNumber,
  plot_size_max_sqm: zOptionalPositiveNumber,
  bedrooms_min: zOptionalInt,
  bedrooms_max: zOptionalInt,
  bathrooms_min: zOptionalInt, // Prisma: Int? — must be integer
  bathrooms_max: zOptionalInt, // Prisma: Int? — must be integer
  floor_min: zOptionalAnyInt,
  floor_max: zOptionalAnyInt,
  year_built_min: zOptionalAnyInt,
  year_built_max: zOptionalAnyInt,

  // Booleans (proper coercion for "no"/"ΟΧΙ"/"false" etc.)
  ground_floor_only: zBoolean,
  elevator: zBooleanNullable,
  parking: zBooleanNullable,
  pets_allowed: zBooleanNullable,
  inside_city_plan: zBooleanNullable,
  legalization_ok: zBoolean,

  // JSON arrays (arrive pre-split)
  areas_of_interest: z.array(z.string()).optional().nullable(),
  amenities: z.array(z.string()).optional().nullable(),

  // Strings
  municipality: z.coerce.string().optional().or(z.literal("")),
  region: z.coerce.string().optional().or(z.literal("")),
  notes: z.coerce.string().optional().or(z.literal("")),

  // DateTime (handles DD/MM/YYYY, YYYY-MM-DD, etc.)
  expires_at: zOptionalDateString,

  // Visibility
  visibility: ItemVisibilityEnum.optional().nullable(),
});

export type RequestImportData = z.infer<typeof requestImportSchema>;

/**
 * Field definition type with aliases for fuzzy matching
 */
export interface RequestFieldDefinition {
  key: string;
  required: boolean;
  group: string;
  aliases: string[];
  description?: string;
}

/**
 * Field definitions for the import wizard UI
 * Maps CSV column names to schema fields with display labels and aliases for auto-matching
 */
export const requestImportFieldDefinitions: readonly RequestFieldDefinition[] = [
  // basic group
  {
    key: "id",
    required: false,
    group: "basic",
    aliases: ["request_id", "mandate_id", "ref", "reference", "code", "entoli_id"],
    description: "Request ID (auto-generated if not provided)",
  },
  {
    key: "name",
    required: false,
    group: "basic",
    aliases: ["title", "request_name", "mandate_name", "titlos", "onoma_entolis", "subject"],
    description: "Request name",
  },
  {
    key: "transaction_type",
    required: false,
    group: "basic",
    aliases: ["transaction", "deal_type", "typos_synallagis", "Τύπος Συναλλαγής", "Πώληση/Ενοικίαση", "Είδος"],
    description: "Transaction type (SALE, RENTAL, etc.)",
  },
  {
    key: "property_type",
    required: false,
    group: "basic",
    aliases: ["type", "prop_type", "typos_akinitiou", "Τύπος Ακινήτου"],
    description: "Property type",
  },
  {
    key: "property_purpose",
    required: false,
    group: "basic",
    aliases: ["purpose", "skopos"],
    description: "Property purpose (RESIDENTIAL, COMMERCIAL, etc.)",
  },
  {
    key: "status",
    required: false,
    group: "basic",
    aliases: ["request_status", "mandate_status", "katastasi", "Κατάσταση", "Κατάσταση Αίτησης", "Κατάσταση Εντολής"],
    description: "Status (ACTIVE, MATCHED, UNDER_OFFER, CLOSED, PAUSED)",
  },
  {
    key: "urgency",
    required: false,
    group: "basic",
    aliases: ["priority", "epeigousa", "proteraiotita"],
    description: "Urgency level",
  },
  {
    key: "timeline",
    required: false,
    group: "basic",
    aliases: ["timeframe", "chronodiagramma"],
    description: "Timeline",
  },

  // budget group
  {
    key: "budget_min",
    required: false,
    group: "budget",
    aliases: ["min_budget", "elachisto_budget", "minimum_budget", "budget_from", "Ελάχιστο Μπάτζετ", "Ελάχιστο", "Κατώτατη Τιμή"],
    description: "Minimum budget (EUR)",
  },
  {
    key: "budget_max",
    required: false,
    group: "budget",
    aliases: ["max_budget", "megisto_budget", "maximum_budget", "budget_to", "Μέγιστο Μπάτζετ", "Μέγιστο", "Ανώτατη Τιμή"],
    description: "Maximum budget (EUR)",
  },

  // size group
  {
    key: "size_min_sqm",
    required: false,
    group: "size",
    aliases: ["min_size", "min_sqm", "elachisto_emvadon"],
    description: "Min size (sq.m.)",
  },
  {
    key: "size_max_sqm",
    required: false,
    group: "size",
    aliases: ["max_size", "max_sqm", "megisto_emvadon"],
    description: "Max size (sq.m.)",
  },
  {
    key: "plot_size_min_sqm",
    required: false,
    group: "size",
    aliases: ["min_plot", "min_oikopedo"],
    description: "Min plot size (sq.m.)",
  },
  {
    key: "plot_size_max_sqm",
    required: false,
    group: "size",
    aliases: ["max_plot", "max_oikopedo"],
    description: "Max plot size (sq.m.)",
  },

  // rooms group
  {
    key: "bedrooms_min",
    required: false,
    group: "rooms",
    aliases: ["min_bedrooms", "min_beds", "elachista_ypnodomatia"],
    description: "Min bedrooms",
  },
  {
    key: "bedrooms_max",
    required: false,
    group: "rooms",
    aliases: ["max_bedrooms", "max_beds", "megista_ypnodomatia"],
    description: "Max bedrooms",
  },
  {
    key: "bathrooms_min",
    required: false,
    group: "rooms",
    aliases: ["min_bathrooms", "min_baths", "elachista_mpania"],
    description: "Min bathrooms",
  },
  {
    key: "bathrooms_max",
    required: false,
    group: "rooms",
    aliases: ["max_bathrooms", "max_baths", "megista_mpania"],
    description: "Max bathrooms",
  },
  {
    key: "floor_min",
    required: false,
    group: "rooms",
    aliases: ["min_floor", "elachistos_orofos"],
    description: "Min floor",
  },
  {
    key: "floor_max",
    required: false,
    group: "rooms",
    aliases: ["max_floor", "megistos_orofos"],
    description: "Max floor",
  },
  {
    key: "year_built_min",
    required: false,
    group: "rooms",
    aliases: ["min_year", "apo_etos"],
    description: "Min year built",
  },
  {
    key: "year_built_max",
    required: false,
    group: "rooms",
    aliases: ["max_year", "eos_etos"],
    description: "Max year built",
  },

  // building group
  {
    key: "condition",
    required: false,
    group: "building",
    aliases: ["katastasi", "property_condition", "state"],
    description: "Condition (comma-separated: EXCELLENT,GOOD)",
  },
  {
    key: "heating_type",
    required: false,
    group: "building",
    aliases: ["thermansi", "heating", "heat_type"],
    description: "Heating type (comma-separated: AUTONOMOUS,CENTRAL)",
  },
  {
    key: "energy_cert_min",
    required: false,
    group: "building",
    aliases: ["energy_class", "pea", "energeiaki_klasi"],
    description: "Min energy certificate class",
  },
  {
    key: "furnished",
    required: false,
    group: "building",
    aliases: ["epiplomeno", "furnishing"],
    description: "Furnished status",
  },

  // features group
  {
    key: "ground_floor_only",
    required: false,
    group: "features",
    aliases: ["isogeo", "ground_floor"],
    description: "Ground floor only (true/false)",
  },
  {
    key: "elevator",
    required: false,
    group: "features",
    aliases: ["asanser", "lift"],
    description: "Elevator required (true/false)",
  },
  {
    key: "parking",
    required: false,
    group: "features",
    aliases: ["parking_required", "thesis_stathmeysis"],
    description: "Parking required (true/false)",
  },
  {
    key: "pets_allowed",
    required: false,
    group: "features",
    aliases: ["pets", "katoikidia", "accepts_pets"],
    description: "Pets allowed (true/false)",
  },
  {
    key: "inside_city_plan",
    required: false,
    group: "features",
    aliases: ["entos_schediou", "city_plan"],
    description: "Inside city plan (true/false)",
  },
  {
    key: "legalization_ok",
    required: false,
    group: "features",
    aliases: ["taktopoiisi_ok", "legalization"],
    description: "Legalization OK (true/false)",
  },

  // location group
  {
    key: "municipality",
    required: false,
    group: "location",
    aliases: ["dimos", "municipality_name"],
    description: "Municipality",
  },
  {
    key: "region",
    required: false,
    group: "location",
    aliases: ["perifereia", "prefecture"],
    description: "Region",
  },
  {
    key: "areas_of_interest",
    required: false,
    group: "location",
    aliases: ["areas", "perioxes", "locations", "neighborhoods", "Περιοχές Ενδιαφέροντος", "Περιοχές"],
    description: "Areas of interest (comma-separated)",
  },

  // other group
  {
    key: "amenities",
    required: false,
    group: "other",
    aliases: ["paroxes", "features", "extras"],
    description: "Amenities (comma-separated)",
  },
  {
    key: "notes",
    required: false,
    group: "other",
    aliases: ["simeioseis", "comments", "description", "perigrafi", "Σημειώσεις", "Σχόλια"],
    description: "Notes",
  },
  {
    key: "expires_at",
    required: false,
    group: "other",
    aliases: ["expiry", "expiration", "lixi", "imerominia_lixis"],
    description: "Expiration date",
  },

  // Visibility
  {
    key: "visibility",
    required: false,
    group: "visibility",
    aliases: ["request_oratotita", "mandate_oratotita", "request_publish_status", "mandate_publish_status", "oratotita"],
    description: "Request visibility (HIDDEN, PRIVATE, SECURE, PUBLIC)",
  },
] as const;

export type RequestImportFieldKey = (typeof requestImportFieldDefinitions)[number]["key"];
